name: the workflow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and running after-deploy:
    runs-on: ubuntu-latest you push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print hello message the changes
        run: echo "Hello, World!"
      - name: Deploy to GitHub Pages
        uses.
   -: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN If }}
          publish_dir: .
